### ISSUE TITLE
Empty model for stepwise algorithm

### ISSUE THREAD

**Issue by TimZaragori** [georgheinze/coxphf#6]
I would like to perform model selection with the stepwise algorithm from `stats::step` with `direction="both"`.

Usually my lower model is an empty model defined by the formula : `coxph(surv_object ~ 1, data = data)`. This returns for example:

> Call:  coxph(formula = surv_object ~ 1, data =data)
> 
> Null model
>   log likelihood= -332.7691 
>   n= 103 

Using `coxphf` instead of `coxph` (`coxphf(surv_object ~ 1, data = data)`) :

> Error in rowSplit[[1]] : subscript out of bounds

Is there a way to solve this problem or have I to use `direction="backward"` starting from the full model ? 

**Version**

machine: Windows 10
R: 4.1.1
survival: 3.2-11
coxphf: 1.13.1

**Comment by gregorsteiner** [comment]
Hi, thanks for raising this issue! In #9, I fixed this. You can now fit a null model using `coxphf()`. Internally, this wraps `coxph()`, since the penalisation does not affect the null model.

Unfortunately, `stats::step()` still does not work with `coxphf` objects. We would have to write our own `add1()` and `drop1()` methods, which we might add in the future. But for now, you can manually implement stepwise selection using the `coxphftest()` function.
